name: pintrest_data_pipeline
channels:
  - defaults
dependencies:
  - python=3.11
  - psycopg2=2.9
  - sqlalchemy=2.0
  - requests=2.32
  - boto3=1.34
  - pyyaml=6.0
  - pymysql=1.0
  # - ipykernel=6.29

